### ISSUE TITLE
episode comment where no episode mentioned

### ISSUE THREAD

**Issue by nthitz** [HeadlessChild/reddit-episode-bot#1]
https://www.reddit.com/r/seinfeld/comments/3lucxs/decided_to_go_with_a_gene_pick/cv9rssi?context=10000

the bot comments on someone who was using numbers but wasn't referencing an episode

**Comment by rexberg** [comment]
Thank you for mention it.
I have seen it respond to several comments that was using numbers but not an reference to an season and episode.

Will look into it.

**Comment by rexberg** [comment]
It very unfortunate because for this comment:

"i think you are mistaking this Weekend at Bernie's 2 quote for the home alone 2 quote George makes regarding the sequel.
the gene pick was bernies 2 not 1. OP is a fag and onetimeonly79 is true hero."

The regex will match an "s" with a number following it, then whatever chars following ending with "episode" or and "e" and then a number after.

"Bernie's 2 quote for the home alone 2", will match because it's basically "...s 2 <random chars> ...e 2".

It's a faulty regex pattern and I will look into it.
